### ISSUE TITLE
Feeding the javascript player with a h264 hardware encoded file 

### ISSUE THREAD

**Issue by ghost** [joelam789/sharp-broadcast#2]
Hi again, 

I'm open . So, I have the following server based on Nvidia APIs which do the following:
- it captures a context render buffer on gpu
- Encodes that using hardware acceleration
- finally produce a .h264 file

I'm curious in how can I use your Server to serve that streaming to playerback on Javascript player, since maybe I will have to eliminate the Encoder to not reencoder the file and so adding latency to the process.

**Comment by joelam789** [comment]
The core of **Media Encoder** is **ffmpeg** .
So if your server's output stream could be read by **ffmpeg** , 
then **Media Encoder** should be able to send it to **Media Server** .

You may refer to official doc (http://ffmpeg.org/ffmpeg-protocols.html) to find a solution for your server.

Actually you can send streams to **Media Server** with **ffmpeg** directly.
**Media Encoder** is just like a GUI front-end of **ffmpeg** .

Here is an example:

`
ffmpeg -re -i "http://abclive.abcnews.com/i/abc_live4@136330/index_2500_av-p.m3u8"  -s 1280x720 -r 20 -b:v 1280k  -an -vcodec libx264 -tune zerolatency -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0  -pix_fmt yuv420p -g 50 -threads 1  -f h264 http://127.0.0.1:9310/desktop/h264/1280x720x20@1280kbps
`

The last URL in the command line above is the address of **Media Server**.

**Comment by joelam789** [comment]
I do not recommend that you bypass ffmpeg.
Because the javascript player decodes h.264 data with library **broadway.js** .
And **broadway.js** expects a restricted h.264 format.
(see https://github.com/mbebenita/Broadway#encoding-video)

**Comment by ghost** [comment]
So I'm trying here with my ffmpeg the following (Sorry I started early work with ffmpeg):

`ffmpeg -re -i "C:\Program Files (x86)\NVIDIA Corporation\NVIDIA Capture SDK\datasets\CUDADecode\teste\test-720p.h264" -s 1280x720 -r 20 -b:v 1280k -an -vcodec libx264 -tune zerolatency -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -pix_fmt yuv420p -g 50 -threads 1 -f h264 http://127.0.0.1:9310/desktop/h264/1280x720x20@1280kbps`

The **Media Server** gets the ffmpeg command, but I see nothing in the browser.  The **client count** in  **Media Server** is **0**.

**Comment by ghost** [comment]
I already fixed that. It was missing **desktop-4800**

`ffmpeg -re -i "C:\Program Files (x86)\NVIDIA Corporation\NVIDIA Capture SDK\datasets\CUDADecode\teste\test-720p.h264" -s 800x600 -r 30 -b:v 1280k -an -vcodec libx264 -tune zerolatency -pass 1 -coder 0 -bf 0 -flags -loop -wpredp 0 -pix_fmt yuv420p -g 80 -threads 1 -f h264 http://127.0.0.1:9310/desktop,desktop-48000,desktop-44100/h264/800x600x20@1280kbps`

**Comment by joelam789** [comment]
Well done man!

But the last path segment of the URL is still not **100%** correct.
The parameters  "**-s 800x600 -r 30 -b:v 1280k**" should match "**800x600x30@1280kbps**" .
